config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  resources :orders
  resources :products,except: [:new,:update, :edit] do
    resources :orders, except: [:index]
  end
  get"/mes-notifications", to: "products#notifications"
  get "/mes-recettes", to: "products#recipes"
  get "/mes-recettes/new", to: "products#new", as: "new_recipe"
  get "/mes-recettes/:id/edit", to: "products#edit", as: "edit_recipe"
  patch "/products/:id", to: "products#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :buyer, foreign_key: :buyer_id,  class_name: "User"
  belongs_to :product

  validates :status, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :seller, foreign_key: :seller_id,  class_name: "User"
  has_one_attached :photo
  has_many :orders
  validates :name, :description, :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo

  has_many :orders, through: :products
  validates :name, :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all.order(id: :desc)
    @users = User.all
    @products = Product.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)
    @product = Product.find(params[:product_id])

    @order.product_id = @product.id
      @order.buyer_id = current_user.id

    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_path, notice: "Order was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:status, :quantity, :customization_message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @disable_nav = true
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    skip_before_action :authenticate_user!, only: [ :index, :show ]
    before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
    @users = User.all
    #@username = User.find(@product.seller_id).name
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.seller_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to mes_recettes_path, notice: "Product was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to mes_recettes_url, notice: "product was successfully destroyed." }
    end
  end

  def recipes
    @products = Product.all.where(seller_id: current_user.id)
  end

  def notifications
    @products = Product.where(seller_id: current_user.id)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KhoubzDialDar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" unless @disable_nav%>
    <%= render "shared/flashes" %>
    <div class="<%= !current_page?(root_path) ? 'mymain-wrapper' : ''%>">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <script src="https://kit.fontawesome.com/2340d02f64.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for @order, url: "/products/#{params[:product_id] }/orders", method: 'post' do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

 <div class="form-inputs">
    <%= f.input :quantity %>
    <%= f.input :customization_message %>


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
  <tr>
    <td>
    Nom : <%=  @users.find(@products.find(order.product_id).seller_id).name %> <br/>
    Tel : <%=   @users.find(@products.find(order.product_id).seller_id).phone_number %> <br/>
    Email :<%=  @users.find(@products.find(order.product_id).seller_id).email %></td>
    <td> <%= order.customization_message %></td>
    <td><%= order.quantity %></td>
    <td>
      <span class="<%= order.status.downcase %>"><%= order.status %></span>
    </td>
  </tr>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
  
</div>

app/views/orders/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container" >
  <strong><h1 class="text-center">Mes commandes</h1></strong>
  <br>
  <table id="orders">
    <thead>
      <tr>
        <th>Client</th>
        <th>Message</th>
        <th>Quantité</th>
        <th>Statut</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
          <%= render("order", order: order)  %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="container form-wrapper">

  <h1>Nouvelle commande:</h1>

  <%= render "form", order: @order %>
  <br>
  <br>
<a class="fa-solid fa-arrow-left" href="/orders" style="text-decoration:none; color:orange; family-font:'Open Sans'; font-weight:bold; font-size: medium;"> Mes commandes </a>
</div>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @order %>

<div>
  <%= link_to "Edit this order", edit_order_path(@order) %> |
  <%= link_to "Back to orders", orders_path %> | 

  <%= button_to "Destroy this order", @order, method: :delete %>
</div>

app/views/pages/home.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon-transparent fixed-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
    <div class="container-fluid">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag asset_path 'KHOBZ Logo.png' %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "Home",root_path, class: "text-warning pe-3 nav-link" %>
              </li>
              <li class="nav-item ">
              <%= link_to "Nos recettes", "/products", class: "text-warning pe-3 nav-link" %>
            </li>
              <li class="nav-item ">
              <%= link_to "Notifications", "/mes-notifications", class: "text-warning pe-3 nav-link" %>
            </li>
            <li class="nav-item dropdown">
              <% if !current_user.photo.key.nil? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% else %>
                <%= image_tag "https://kitt.lewagon.com/placeholder/users/Adam-Aber", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <% end %>
              <div class="gold-background dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Mes recettes", "/mes-recettes", class: "gold-background dropdown-item" %> <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "gold-background dropdown-item" %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="banner d-flex mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path  'https://images.unsplash.com/photo-1533117307029-74a8b35848cb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80' %>);">
    <div class="container-home">
      <div class="proposition-value">
        <h1>Le pain <strong><span class="text-warning">le plus frais</span></strong> est <strong>prêt</strong>!</h1>
        <p class="secondary-sentence">Commandez votre <span class="underline"> Homemade</span> pain préféré</p>
      </div>
      <a class="btn btn-flat btn-warning" href="<%= products_path %>">J'achète maintenant!</a>
    </div>
  </div>


  <section>
      <div class="magrid ms-4">

        <div class="ma-design p-2" style="background-image: url('<%= asset_path("tile.png") %>');background-position: center;background-size: contain;background-repeat: no-repeat;">
          <div class="card-trip p-6">
              <%= image_tag asset_path 'authentic.jpg'%>
              <h2>Une expérience traditionnelle authentique</h2>
              <p>Achetez du pain fait maison et personnalisez le à votre goût.</p>
            </div>
        </div>

        <div class="ma-design p-2" style="background-image: url('<%= asset_path("tile.png") %>');background-position: center;background-size: contain;background-repeat: no-repeat;">
          <div class="card-trip p-6">
            <%= image_tag asset_path 'https://images.unsplash.com/photo-1517686469429-8bdb88b9f907?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'%>
            <h2>Personnalisé à votre goût</h2>
            <p>Nous assurons votre satisfaction avec les commandes personnalisées faîtes un jour à l'avance !</p>
          </div>
        </div>

        <div class="ma-design p-2" style="background-image: url('<%= asset_path("tile.png") %>');background-position: center;background-size: contain;background-repeat: no-repeat;">
          <div class="card-trip p-6">
            <%= image_tag asset_path 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'%>
            <h2>Une grande communauté de vendeurs</h2>
            <br>
            <p>Même VOUS vous pouvez devenir vendeur.</p>
          </div>
        </div>

      </div>
  </section>

  <section class="my-5">
    <div class="yellow-bg section">
      <h3 class="numbers-title yellow-txt">Best</h3>
        <div class="vector-container">
          <%= image_tag asset_path 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80', class: "w-50"%>
        </div>
      <h3 class="numbers">Seller</h3>
    </div>

    <div class="blue-bg section">
      <h3 class="numbers-title blue-txt">100%</h3>
        <div class="vector-container">
          <%= image_tag asset_path 'https://images.unsplash.com/photo-1549057188-efd70413345e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1173&q=80', class: "w-50"%>
        </div>
      <p class="numbers">Fait maison</p>
    </div>
  </section>


  <div class="container-carousel">
    <div class="carousel-section">
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="carousel-bottom">
              <%= image_tag asset_path 'https://images.unsplash.com/photo-1471646174523-327e108889e7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1172&q=80'%>
            </div>
          </div>
          <div class="carousel-item">
            <div class="carousel-bottom">
              <%= image_tag asset_path 'https://images.unsplash.com/photo-1603777953733-c3f9b2533bf8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'%>
            </div>
          </div>
          <div class="carousel-item">
            <div class="carousel-bottom">
              <%= image_tag asset_path 'https://images.unsplash.com/photo-1603779702245-0bfe6bb1cd75?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'%>
            </div>
          </div>
           <div class="carousel-item">
            <div class="carousel-bottom">
              <%= image_tag asset_path 'https://images.unsplash.com/photo-1512684974096-473a769cde8e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80'%>
            </div>
          </div>
           <div class="carousel-item">
            <div class="carousel-bottom">
              <%= image_tag asset_path 'https://images.unsplash.com/photo-1521931206836-2265cd656a5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1174&q=80'%>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
  </div>


  <section class="home-testimonial carousel-section">
        <div class="row d-flex justify-content-center testimonial-pos">
            <div class="col-md-12 pt-4 d-flex justify-content-center">
                <h1>Avis</h1>
            </div>
            <div class="col-md-12 d-flex justify-content-center">
                <h2>Explorez les expériences de nos clients</h2>
            </div>
        </div>
        <section class="home-testimonial-bottom">
            <div class="testimonial-inner">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-4 style-3">
                        <div class="tour-item ">
                            <div class="tour-desc bg-white">
                                <div class="tour-text color-grey-3 text-center">&ldquo;La mission principale de Khobz Dar est de donner à tout le monde l'opportunité de partager ses recettes de pain uniques avec le reste du monde.&rdquo;</div>
                                <div class="d-flex justify-content-center pt-2 pb-2"><img class="tm-people" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80" alt=""></div>
                                <div class="link-name d-flex justify-content-center">Assia</div>
                                <div class="link-position d-flex justify-content-center">Étudiante</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 style-3">
                        <div class="tour-item ">
                            <div class="tour-desc bg-white">
                                <div class="tour-text color-grey-3 text-center">&ldquo;Khobz Dar m'a permis de gagner des revenus complémentaires afin d'arrondir les fins de mois. C'est une bonne opportunité pour les étudiants de se faire un peu d'argent de poche pendant leur temps libre.&rdquo;</div>
                                <div class="d-flex justify-content-center pt-2 pb-2"><img class="tm-people" src="https://images.unsplash.com/photo-1544723795-3fb6469f5b39?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=689&q=80" alt=""></div>
                                <div class="link-name d-flex justify-content-center">Ahmed</div>
                                <div class="link-position d-flex justify-content-center">Étudiant</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 style-3">
                        <div class="tour-item ">
                            <div class="tour-desc bg-white">
                                <div class="tour-text color-grey-3 text-center">&ldquo;Grâce a Khobz Dar, je n'ai plus besoin d'aller à la boulangerie quotidiennement, maintenant je peux en un seul clic commander du pain frais fait maison.&rdquo;</div>
                                <div class="d-flex justify-content-center pt-2 pb-2"><img class="tm-people" src="https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80" alt=""></div>
                                <div class="link-name d-flex justify-content-center">Karima</div>
                                <div class="link-position d-flex justify-content-center">Employée</div>
                            </div>
                        </div>
                    </div>

        </section>
  </section>

app/views/products/_form.html.erb

<%= simple_form_for @product, method: method do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

 <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
  </div>


  <div class="form-actions">
    <%= f.submit "Valider" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container form-wrapper" >

<h1>Editing product</h1>

<%= render "form", product: @product, method: "patch" %>

<br>

<div>
  <%= link_to "Retour", products_path %>

</div>
</div>

app/views/products/index.html.erb

<div id="index" class="container">
  <p style="color: green"><%= notice %></p>
  <div class="d-flex justify-content-around mb-5">
      <h1 id="title"> Nos pains frais</h1>
    </div>
    <div class="grid">
      <% @products.each do |product| %>
        <%= link_to product_path(product) do %>
        <%# added the line above so that the whole card becomes clickable %>
          <div class="products" style="text-decoration:none" >
              <div class="card-trip">
                <% if product.photo.attached? %>
                  <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
                <% else %>
                  <%= cl_image_tag "https://tasteofmaroc.com/wp-content/uploads/2017/08/batbout-2-edit2.jpg", class: "projcard-img", crop: :fill %>
                <% end %>
                <div class="card-trip-infos">
                 <%= cl_image_tag product.seller.photo.key, class:"card-trip-user avatar-bordered"  %>
                </div>
                  <div class="d-flex flex-column">
                    <p><h2><%= product.name %></h2></p>
                    <p><%= product.price %> MAD</p>
                  </div>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
</div>

app/views/products/notifications.html.erb
<div id="notifs" class="container">
<br>
<br>
  <div class="d-flex justify-content-around mb-5">
  <h1>Commandes</h1>
  </div>
  <% @products.each do |product| %>
  <div class="wrapper">
      <%# added the line above so that the whole card becomes clickable %>
    <%= link_to product_path(product) do %>
      <div class="card-product">
        <% if product.photo.attached? %>
          <%= cl_image_tag product.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <%= cl_image_tag "https://tasteofmaroc.com/wp-content/uploads/2017/08/batbout-2-edit2.jpg", height: 300, width: 400, crop: :fill %>
        <% end %>
        <div class="card-product-infos">
         <div class="details">
          <h2><%= product.name %></h2>
          <p><%= product.description %></p>
         </div>
          <div class="infos">
            <p> <%= product.price %> MAD <i class="fa-solid fa-tag"></i></p>
            <span> <i class="fa-solid fa-sack-dollar"></i> <%=  product.orders.where("status ilike 'Delivered'").count %> pièce(s) Vendus</span>
            <span><i class="fa-regular fa-clock"></i> <%= product.orders.where("status ilike 'unDelivered' OR status ilike 'pending'").count %> pièce(s) en attente</span>
          </div>
        </div>
      </div>
    <%end%>
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne<%= product.id %>" aria-expanded="false" aria-controls="collapseOne<%= product.id %>">
            Détails de commandes ( <%= product.orders.count %> )
          </button>
        </h2>
        <div id="collapseOne<%= product.id %>" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <% product.orders.each do |order| %>
              <p>Statut: <%= order.status %></p>
              <p>Quantité: <%= order.quantity %></p>
              <p>Message de personnalisation: <%= order.customization_message %></p>
              <p>Nom du client:<%= order.buyer.name %></p>
              <p>Email:<%= order.buyer.email %></p>
              <p>Numéro de téléphone:<%= order.buyer.phone_number %></p>
              <hr/>
            <% end %>
          </div>
        </div>
      </div>
    </div>
      </div>
  <%end%>
</div>

app/views/products/recipes.html.erb
<div class="container">
  <div class="d-flex justify-content-around mb-5">
      <h1>Mes recettes</h1>
    </div>
    <div class="grid">
      <% @products.each do |product| %>
        <%= link_to product_path(product) do %>
        <%# added the line above so that the whole card becomes clickable %>
          <div class="products" style="text-decoration:none" >
              <div class="card-trip">
                  <% if product.photo.attached? %>
                    <%= cl_image_tag product.photo.key, class: "projcard-img", crop: :fill %>
                  <% else %>
                    <img src="https://images.unsplash.com/photo-1586765501019-cbe3973ef8fa?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1168&q=80">
                  <% end %>
                <div class="card-trip-infos">
                 <%= cl_image_tag product.seller.photo.key, class:"card-trip-user avatar-bordered"  %>
                </div>
                  <div class="d-flex flex-column">
                    <p><h2><%= product.name %></h2></p>
                    <p><%= product.price %> MAD</p>
                  </div>
              </div>
          </div>
        <% end %>
      <% end %>
       <%= link_to new_recipe_url do %>
          <div class="products" style="text-decoration:none" >
              <div class="card-trip add-product">
                  <img src="https://i.pinimg.com/originals/3a/dc/db/3adcdb390790baf3dd3c0638868d0e42.jpg">
                <span><i class="fa-regular fa-square-plus"></i></span>
                <div class="card-trip-infos">
                </div>
                  <div class="d-flex flex-column">
                    <h2>Ajouter une nouvelle recette</h2>
                  </div>
              </div>
          </div>
        <% end %>
    </div>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="show" class="container">
  <a class="fa-solid fa-arrow-left" href="/products" style="text-decoration:none; color:orange; family-font:'Open Sans'; font-weight:bold; font-size: medium; ">
    Liste de produits
  </a>
  <%= render "product" %>

  <% if current_user%>
    <% if @product.seller_id == current_user.id%>
    <a href="<%= edit_recipe_path(@product.id) %>" style="position:absolute; right:20px; top:250px; color:black">
    <i class="fa-solid fa-wand-magic-sparkles"></i></a>
    <% end %>
  <% end %>

  <a href="<%= new_product_order_path(@product)%>"style="position:absolute; right:80px; top:250px; color:black">
  <i class="fa-sharp fa-solid fa-basket-shopping"></i></a>

  <% if current_user%>
    <% if @product.seller_id == current_user.id%>
      <%= link_to  product_path(@product), data: {turbo_method: :delete}, style: "position: absolute;  right:140px; top:250px; color:black" do %>
        <i class="fa-solid fa-trash-can"></i>
      <% end %>
    <% end %>
  <% end %>
</div>